version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset