version = 0.1
[default.deploy.parameters]
stack_name = "Ike-Api-SMS-Cobros-Wal-Develop"
resolve_s3 = true
s3_prefix = "Ike-Api-SMS-Cobros-Wal-Develop"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
